### ISSUE TITLE
Missing some necessary files

### ISSUE THREAD

**Issue by yuan-zm** [saltoricristiano/lidog#3]
Hi @saltoricristiano,

Thanks for sharing this work!

You may miss uploading some files, such as `configs/common/dataset_paths.yaml`, `_resources` (weight_path), and some data mapping files.

**Comment by saltoricristiano** [comment]
Hi @yuan-zm,

Thank you for the interest in our work!

Damn, I apologize for the issue. I will try to fix it in the following weeks as I'm pretty busy! If you are in a rush and cannot wait, you can find most of the mapping files [here](https://github.com/saltoricristiano/gipso-sfouda/tree/main/utils/_resources) and part of the weights from [here](https://github.com/saltoricristiano/cosmix-uda/tree/main/utils/datasets/_weights).

Sorry again and best regards,
@saltoricristiano

**Comment by yuan-zm** [comment]
Thank you, I will try it.

**Comment by Nuyoah0123** [comment]
> Thank you, I will try it.

Hello, have you reproduced it successfully? I encountered the same problem when I tried to reproduce this code.

**Comment by yuan-zm** [comment]
> > Thank you, I will try it.
> 
> Hello, have you reproduced it successfully? I encountered the same problem when I tried to reproduce this code.

Yes, I ran it with the file provided by the author before, but it was so long ago that I forgot what I modified. Sorry.

**Comment by yuan-zm** [comment]
> > Thank you, I will try it.
> 
> Hello, have you reproduced it successfully? I encountered the same problem when I tried to reproduce this code.

Hi @Nuyoah0123, I found my modified file recently. 

Just create a file to debug this project.

configs/common/dataset_paths.yaml

```

datasets:
  name: 
    - SemanticKITTI
    - SemanticKITTI-BEV
  data_path:
    - /home/user1/dataset/semanticKITTI/dataset/
    - /home/user1/dataset/semanticKITTI/dataset/

  mapping_path:
    - _resources/semantickitti2common.yaml
    - _resources/semantickitti2common.yaml

  weights_path:
    - dataset_weight/semantic-kitti.npy
    - dataset_weight/semantic-kitti-BEV.npy
```

Actually, the weights_path is invalid. The code provided by the author will automatically create the weights file.
